version: '3'

services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - /home/ec2-user/certs/certbot-etc:/etc/letsencrypt
      - /home/ec2-user/certs/certbot-var:/var/lib/letsencrypt
    networks:
      - shared-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ec2-user/certs/certbot-etc:/etc/letsencrypt
      - /home/ec2-user/certs/certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email damish.shah@gmail.com --agree-tos --no-eff-email --force-renewal -d damishshah.com  -d www.damishshah.com 
    # You can use the staging version of certbot for testing, so we don't get throttled.
    # command: certonly --webroot --webroot-path=/var/www/html --email damish.shah@gmail.com --agree-tos --no-eff-email --staging -d damishshah.com  -d www.damishshah.com 

volumes:
  web-root:
      driver: local
      driver_opts:
        type: none
        device: /home/ec2-user/damishshah.github.io/
        o: bind

networks:
  shared-network:
    driver: bridge